baseurl: ''
url: 'https://clicfit.co'
name: Vacaciones Opitas
title: Vacaciones Opitas | Viajes y Turismo en el Huila
description: Blog de viajes y turismo en el Huila, Colombia. Encuentra información sobre destinos turísticos, hoteles, restaurantes y actividades para hacer en el departamento del Huila.
permalink: /:slug/

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
